FROM golang:1.24-alpine

RUN apk add --no-cache gcc musl-dev librdkafka-dev pkgconf

WORKDIR /app

# Dependencies önce kopyalanır (layer caching için)
COPY go.mod go.sum ./
RUN go mod download

# Kod volume olarak mount edilecek, bu sadece başlangıç için
COPY . .

EXPOSE 8088

# CGO enabled olarak çalıştır (Kafka için gerekli)
CMD ["sh", "-c", "CGO_ENABLED=1 go run -tags dynamic ."]
